### ISSUE TITLE
Aggiungere a gruppi!

### ISSUE THREAD

**Issue by Stefano12345** [PietroArado/rss-ifttt-telegram#1]
Ciao, volevo sapere se fosse possibile aggiungere il bot ai gruppi per fare in modo che invii i messaggi anche lì. È possibile? 
Spero in tuo risposte, grazie.

**Comment by PietroArado** [comment]
Ciao, sì, dovrebbe essere possibile aggiungerlo ai gruppi. Basta inviare il comando di sottoscrizione all'interno del gruppo stesso. Ad ogni modo, se i messaggi devono essere inviati solo in un gruppo, è più rapido utilizzare solo IFTTT.
Scusa se ho impiegato molto per rispondere, saluti.
